### PR TITLE
Updated menu item links to respective product docs repo links

### PR DESCRIPTION
**Pull request by gunamata**

### CODE REVIEW

**Review by sunilarjun — APPROVED** [review]
Approving after testing the change locally and the dropdown displayed the Turtles Product Docs repo as the first link, Turtles Product Docs repo issues as the second link, and a contribution link third. Thanks Guna!

**Comment by btat** [comment]
Are we going under the assumption that all content sources will remove the `documentation` and `product documentation` substrings from the component title? If not, we end up with truncated entries.

issue-menu

**Review by btat — APPROVED** [review]
Adding approval with the assumption we'll use shorter component names.

**Review by LucasSaintarbor — APPROVED** [review]

**Comment by LucasSaintarbor** [comment]
Approved. Working on my end as well. Thanks Guna! 

Screenshot 2024-08-30 at 2 51 25 PM

**Comment by gunamata** [comment]
> Are we going under the assumption that all content sources will remove the `documentation` and `product documentation` substrings from the component title? If not, we end up with truncated entries.
> 
> issue-menu

Yes, we remove `product-documentation` from names to keep the name shorter

**Pull request merged**
